.config_block: &config_block
  account_number: <%= ENV['HERMES_BASECAMP_ACCOUNT_NUMBER'] %>
  client_id: <%= ENV['HERMES_BASECAMP_CLIENT_ID'] %>
  client_secret: <%= ENV['HERMES_BASECAMP_CLIENT_SECRET'] %>
  refresh_token: <%= ENV['HERMES_BASECAMP_REFRESH_TOKEN'] %>
  access_token: <%= ENV['HERMES_BASECAMP_ACCESS_TOKEN'] %>
  redirect_uri: ''

production:
  <<: *config_block

development:
  <<: *config_block