name: Release

on:
  push:
    tags:
      - v*

jobs:
  publish_rails:
    runs-on: ubuntu-latest
    name: Build and push rails image
    steps:
      - uses: actions/checkout@v2
      - name: build-push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: runhermes/hermes
          tag_with_ref: true
          tag_with_sha: true
          tags: latest
          dockerfile: Dockerfile

  changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Update Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          addSections: '{"documentation":{"prefix":"**Documentation:**","labels":["documentation"]}}'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Changelog for tag ${{ env.CI_REF_NAME }}
          file_pattern: CHANGELOG.md

  release_notes:
    name: Create Release Notes
    runs-on: ubuntu-latest
    needs: changelog
    steps:
      - uses: FranzDiebold/github-env-vars-action@v2
      - uses: actions/checkout@v2
        with:
          ref: main

      - id: changelog_reader
        uses: mindsers/changelog-reader-action@v1
        with:
          version: ${{ env.CURRENT_VERSION }}
          path: ./CHANGELOG.md

      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.CI_REF_NAME }}
          release_name: ${{ env.CI_REF_NAME }}
          body: ${{ steps.changelog_reader.outputs.log_entry }}
          draft: false
          prerelease: false